### ISSUE TITLE
Car download using Singularity download

### ISSUE THREAD

**Issue by xinaxu** [data-preservation-programs/singularity#104]
## Prerequisite
- [x] #90
- [x] #96
- [x] #97

# Test List
- [ ] Start singularity content provider `singularity run content-provider`
- [ ] For all pieces listed in `singularity dataset list-pieces`
  - [ ] Download using `singularity download <piece_cid>`
  - [ ] Try multithread download using `-j` flag. Downloaded file should resolve to the same hash
  - [ ] [If Inline Preparation disabled] compare the downloaded CAR files with the exported CAR files
  - [ ] [If inline Preparation enabled] use `singularity tool extract-car` to verify the correctness of the CAR files
- [ ] Perform above exercise for local, public S3 and private S3 buckets
  * Use same arguments, i.e. `--s3-region`, `--s3-access-key-id` that is used when adding data source

**Comment by xinaxu** [comment]
Known bug: #72

**Comment by Ng-YanBo** [comment]
Local Done with -J command

![Image](https://github.com/data-preservation-programs/singularity/assets/137220294/47448a1a-b449-483b-8bc2-5eef3abd1a62)

**Comment by xinaxu** [comment]
@Ng-YanBo S3 public and private are not ready for testing yet

**Comment by xinaxu** [comment]
In fact all those tests that are not marked as "testing needed" are not ready for testing but feel free to test and give early feedback

**Comment by xinaxu** [comment]
covered in unit tests
