### ISSUE TITLE
Deal making manual  send

### ISSUE THREAD

**Issue by xinaxu** [data-preservation-programs/singularity#107]
## Prerequisite
- [ ] Have some dataset prepared
- [ ] Have some wallet imported using `singularity wallet import`

# Note
For this test, the storage provider does not have to actually seal those deal. We only need to verify the deal been accepted by the storage provider and has the correct parameters (i.e. price, duration, start time)

# Test List
Use `singularity deal send-manual` to send a single deal to a storage provider
- [ ] Test all options inside `Deal Proposal` section. The proposal payload can be verified in boost deal details

**Comment by Ng-YanBo** [comment]
2 Offline deals received by SPs - it was a small dataset, will close this once retrieval is successful
