### ISSUE TITLE
File Retrieval API

### ISSUE THREAD

**Issue by hannahhoward** [data-preservation-programs/singularity#113]
### User Story

Given an File ID for a previously stored blob of bytes from a datasource, I should be able to retrieve the bytes for that blob, either from the datasource or by retrieving from Filecoin if the data is already deleted from the data source.

#### Handler Signature 

```golang
func RetrieveFile(ctx context.Context, db *gorm.DB, fileID uint64) (io.ReadSeeker, error)
   // ...
}
```

#### HTTP Endpoint

```
GET /api/file/:id/retrieve
```
Returns 200 and response body with file data
**IMPORTANT: Accepts range requests**

#### Handler outline

1. Look up the file from Singularity database, preloading the file ranges
2. Check whether data is still available on datasource
3. If available on data source, simply open the data from the datasource and return handler to read from it
4. If data is not available on data source, read seeker is implemented as follows:
    - stores a current position (initially 0)
    - size is stored on file model, so io.SeekEnd can be implemented with this
    - on read, find file ranges covering current range
       - attempt to retrieve file range from filecoin
           - per singularity rules, every file range fits in a piece
           - essentially, look up all active deals for an file range by joining FileRange -> Chunks -> CARS -> Deals (through piece CID)
           - retrieve the file range as a CAR file through Lassie
             - do a full dag request using the file range's root CID
             - specify providers directly in the Lassie request (which overrides any indexer lookups)
             - optional: limit protocol to just HTTP
             - serialize out to flat file verifying data in the process
          - if file range can fulfull remaining read request, just return relevant range and update position, hold current file range for next read
          - if file range cannot fulfill remaining read request, continuing retrieving further file range until the full read request can be fulfilled

#### HTTP Endpoint Implementation

The HTTP endpoint can simply be implemented using the above handler plus http.ServeContent

#### Implementation notes

This strategy will be able to handle retrieving arbitrarily large files held across multiple Filecoin pieces. At least in theory, it will do so fairly efficiently (executing 1 GB at a time fetches)

#### Error Handling

The simplest path to handling all Filecoin errors is simply to return an error when ReadSeeker.Read is called

However, to cover the case where an file has been deleted on the data source, but NOT stored on filecoin at all, it may make sense to check up front if there are existing Filecoin deals for a given file before returning the reed seeker.

For the case where data for an file is on Filecoin, but not ultimately retrievable any of the SPs, we really can only error at the time of ReedSeeker.Read being called.

**Comment by xinaxu** [comment]
Make sense.

> simply execute an HTTP request to GET /api/items/:id/retrieve with the relevant range for the read request 

Then should it be `ReadSeekCloser` to handle closing the underlying HTTP socket?

> specify providers directly in the Lassie request

do you want to optimize this by proactively checking the online status of SP HTTP endpoint so the request does not end up hitting unhealthy SP. We saw a handful of timeout (>15sec) retrieval result, which can happen anywhere including checking HTTP endpoint from libp2p retrieval protocol call, dial the multiaddr, hit the HTTP endpoint, etc.

Other questions I have are
* what is the retry strategy on backend SP retrieval, i.e. resume from last received bytes when connection is interrupted, or bubble up the error to remote client and let the client handle the retry.

**Comment by xinaxu** [comment]
It seems like we don't really need #36 as part of MVP because you don't need any unixfs node above the 1GB files for retrieval.

**Comment by hannahhoward** [comment]
@xinaxu lassie tracks provider success and optimizes for those that have high success rate. I think this should eventually handle poor HTTP performance. Plus remember this is largely archival use for MVP in motion

**Comment by ribasushi** [comment]
Note that @willscott did [propose something like this to be done on the SP side](https://filecoinproject.slack.com/archives/C042H9KUQLD/p1684831171549229?thread_ts=1684829903.287179&cid=C042H9KUQLD), and ideally Boost should adopt something similar. But given Singularity "owns" all this content, the Boost dependency does not apply.

**Comment by xinaxu** [comment]
Talked to @ribasushi  on this. @hannahhoward let's sync next Monday exploring this

**Comment by hannahhoward** [comment]
@ribasushi 

Fundamentally I think your idea about storing PieceCID trees in singularity is reasonable in the abstract.

I want to tackle the question of what to do here though in a few steps, cause there's a lot to discuss:

1. "I believe using IPLD full-dag semantics to do incremental verification here is a mistake. For stream-retrievals we should be using the stream-hash ( CommP)." Let's start with defining reasons for why IPLD'ing things is a mistake. I can think of a few, but I want alignment on why we feel this way. Some possible reasons I have in my head:
   1. SPs like their piece retrieval cause they can avoid the whole DAGStore / LID / indexing -- so it's easier on them, has potentially wider adoption, and therefore potentially leads to a wider selection of SPs for a potential motion client to choose from.
   2. Storing less data locally in Singularity per piece. Honestly we could probably go higher than level 17 -- maybe as far as 13 which gets us down to just 2KB (at the cost of 4MB chunks which might be a bit large for very small range reeds). Current singularity architecture is storing references to CIDs for all the blocks in some cases, which looks like a lot more than that maybe.

Some non-reasons (want to make sure we all agree on this too):

   1. Avoiding libp2p -- whether we do payload or piece, we're going to be prioritizing HTTP retrievals

2. The next question I'd like to understand is how much additional work is required in Singularity to do this kind of piece retrieval, and how we plan to implement it
   1. The data preparation code in singularity already does IPLD-ificiation of data. As I understand it, and outlined in detail [here](https://github.com/data-preservation-programs/singularity/blob/main/docs/en/technical-architecture/data-preparation.md), singularity breaks blobs up into 1GB IPLD trees, then stores those 1GB parts across potentially multiple pieces (each with 1GB parts from potentially more than one source item), holding root cids for each 1GB chunk.
   2. What is the proposed strategy for going from byte range in an item to byte range(s) in a piece(s), and tying it the sub piece proof? Is the plan to remove IPLD-ification entirely? Or just try to tie the item parts to byte ranges in a piece and adjust them to sub piece proof boundaries?
   3. @xinaxu how much work do you estimate making some of these changes to be?
   4. I also want to account for the fact that we don't currently have code to try a series of piece retrievals when a piece is replicated across many providers, and certainly not code to split up the retrieval (though arguably, a simple "try each provider one by one in a reasonable order" loop is not hard to write)
   
3. Finally, given the reasons to do this, and given the the work involved, we really have two decisions:
   1. Is this the right decision for singularity in general eventually?
   2. Assuming #1, we have a Project Motion MVP we're trying to launch by end of Q3. Can we realistically get this done before launch? Or does it need to be after? What's the migration plan?
   
I'd like to get a final decision on at least the second question in a couple days, and if consensus doesn't quickly emerge in the discussion, let's please schedule a synchronous call to get a decision and keep things moving.

**Comment by willscott** [comment]
I agree with @hannahhoward  that using data segments / commP-based retrievials is something we should file as a separate issue and that we can tackle outside of the current MVP milestone.

It is a non-trivial amount of work. The reason we are heading down the current IPLD-based retrieval path is because lassie is already built and it is the smallest technical lift to get to a working round-trip system.

**Comment by celine3650** [comment]
Xilin will convert this to be a retrieval item on the motion board.

**Comment by celine3650** [comment]
@hannahhoward Could you provide a list of tasks that need improvement to resolve this issue? Thanks!
