### ISSUE TITLE
Do not autobump version now that unified CI manages releases

### ISSUE THREAD

**Issue by masih** [data-preservation-programs/singularity#120]
The unified CI, now integrated in this repo, manages releases and version bumps via `version.json` file. At the same time there is a CI job that tags every push to main.

We should disable that auto tagging and converge on using the unified CI mechanism unless there is a good reason for it.

https://github.com/data-preservation-programs/singularity/blob/563fbc119be6547adc2fd9441b95662e2ba1597e/.github/workflows/autobump.yml#L15

**Comment by xinaxu** [comment]
Makes sense. Removed in #122
