### ISSUE TITLE
Struct tag "default" in handler structs does not appear to do anything

### ISSUE THREAD

**Issue by hannahhoward** [data-preservation-programs/singularity#125]
Several of the structs used with the various handlers contain "default" struct tags for some of their fields.

I assume these feed into Swagger documentation.

However, the values here appear to have no effect. I would imagine if a value has a default, the resulting created object has the default value specified. But in some cases it doesn't, and for required fields, if you leave these values out, they don't take on the expected default values.

**Comment by xinaxu** [comment]
It needs to be using below tag
`binding:"required"`

Generated swagger
```

            "type": "object",
            "required": [
                "maxSize"
            ],
            "properties": {
              ...
            }
```

**Comment by xinaxu** [comment]
Actually you are right, it should get replaced on the server side as requried by openapi spec.

**Comment by xinaxu** [comment]
I'm going through all tags and make corresponding changes
