### ISSUE TITLE
Get all deals statuses for an item

### ISSUE THREAD

**Issue by hannahhoward** [data-preservation-programs/singularity#132]
# Goals

In order to provide all of the statuses for a blob stored with singularity we need to be able to map from Item to every current storage deal that contains an ItemPart from the item.

I expect this to be a sql query (1 or more) with a few joins:

Item ID -> all related item part ids -> all related chunk ids -> all related cars -> all related storage deals

All of these joins are by primary key (and have a foreign key contraint in related table), except for car -> storage deal. For this, the join is on PieceCID.

**Comment by xinaxu** [comment]
That's right. The PieceCID has an index built so it shouldn't have any performance penalty. One difference is that the PieceCID for car is saved as byte array but for deal, it is saved as string. 
My original thinking is that, for deals, some users may want to look at the database and play around with raw SQL. the string presentation of CID makes it easier for them.
Thoughts? @hannahhoward
