### ISSUE TITLE
[Bug]:  READ.me  / Installation instructions

### ISSUE THREAD

**Issue by distora-w3** [data-preservation-programs/singularity#150]
### Description

```text
Issue: 
Additional documentation needed

Context:
The Singularity V1 install documentation was good. As a newbie, I could work through the install page step by step. However, I did run into version issues with Lotus, Boost, and npm. Singularity V2 uses go-lang, and therefore this issue could repeat. 
Examples:
- my current boost node runs go version go1.20.3 (yet the current doc has an example and suggests a starting point of go1.19.7)
- similarly, I ran into an issue with "singularity repl" where an older boost version rejected deals due to a command line option deprication issue
We can help users make a better attempt at installation and subsequently reduce the support requirements for the singularity team.

Recommendation:
The installation page has a section for "get started or prerequisites or minimal requirements."
Example: https://lotus.filecoin.io/lotus/install/prerequisites/
Another example is boost 
 - https://boost.filecoin.io/getting-started  (v2)
 - note the matrix - this is a really good idea and could help focus efforts and ensure the community and support are working to known lanes. Often support issues can be resolved simply by directing a user to a known working lane
 - also notice the "Please make sure you have installed" section

Another good example in the link below are the imagined use cases.
https://lotus.filecoin.io/lotus/get-started/use-cases/

Another issue I ran into with Singularity V1 was related to the .toml files having set port numbers. It would be good to list environment variables and any assumed configuration values. (Especially if intended uses cases are to split out into the use of only certain components)
```

### Steps to Reproduce

None - initial requirement

### Version

First time to project, trying to understand how to install

### Operating System

Linux

### Database Backend

SQLite

**Comment by xinaxu** [comment]
@distora-w3 The most complaints you had is with Singualrity V1. We understand that those are painpoints for V1 installation and we aim to not repeat those mistakes in V2.
We are focusing our effort on V2 hence we are not going to update documentation for V1 anymore. I wonder if the current documentation of V2 solves all your concern above?

> my current boost node runs go version go1.20.3 (yet the current doc has an example and suggests a starting point of go1.19.7)

https://data-programs.gitbook.io/singularity/installation/install-from-source It actually says version 1.19+ . So you reuse the 1.20 already installed with boost. @celine3650 We can improve our documentation to clarify this, i.e.
* Add prerequisites that says golang 1.19+ is the only requirements
* Have similar section like https://boost.filecoin.io/getting-started but ours can be much simplified as we only depends on golang

> I ran into an issue with "singularity repl" where an older boost version rejected deals due to a command line option deprication issue

Singualrity V2 is not depending on any binaries. You don't need to install lotus nor boost along with Singularity V2. Singularity V2 is designed to work without any external dependency, which also means, for any future boost upgrade, it will not break any old version of Singularity.

> Another issue I ran into with Singularity V1 was related to the .toml files having set port numbers.

In V2, all config values are set through either the command line or the environment args. i.e. the database connection string is listed here https://data-programs.gitbook.io/singularity/cli-reference/cli-reference, the concurrency number is listed here https://data-programs.gitbook.io/singularity/cli-reference/run/dataset-worker

Do you still prefer having all environment variables listed on a single page? (which can be quite long)

**Comment by distora-w3** [comment]
Thank you for the reply @xinaxu

Just for clarity
- [1] I am not asking to update Singularity V1, only to apply the lessons learnt to V2. Also, to follow the conventions of Boost & Lotus etc., which are useful forms of documentation.
- [2] I have reviewed the installation instructions for V2 and I am not able to understand the integration with Boost & Lotus lite etc. I note your comment that there are no binary dependencies. This is good. 

Thank  you for the link to the cli. As per the cli reference it states the following. 

```
   Network Support:
     Default settings in Singularity are for Mainnet. You may set below environment values for other network:
       For Calibration network:
         * Set LOTUS_API to https://api.calibration.node.glif.io/rpc/v1
         * Set MARKET_DEAL_URL to https://marketdeals-calibration.s3.amazonaws.com/StateMarketDeals.json.zst
       For all other networks:
         * Set LOTUS_API to your network's Lotus API endpoint
         * Set MARKET_DEAL_URL to empty string
       Switching between different networks with the same database instance is not recommended.
```
The above snippet is precisely the information that would be helpful in the installation section and would help the understanding in point [2] above. This part of the cli tells me the integration elements which would aid understanding when exposed earlier on.

Yes, I see the issue you raise about the long list of environment variables. We could meet in the middle to serve both purposes. Purpose 1, avoid listing all environment variables. 
Purpose 2, creating awareness of the richness of singularity v2 with many options available to improve performance and allow the user to find these options and settings. 

Example text could be written in a similar way to this:

```
Singularity V2 can be configured in many ways. Please see the cli reference for the range of options and environment variables.
The following example shows how you might increase throughput.

$DATASET_WORKER_CONCURRENCY = x  #default is 1
```

**Comment by distora-w3** [comment]
Here is another example of something that needs to be in the doc. It is not obvious how to set up the go echo server on an external standalone system due to the default binding having been set localhost

```
./singularity run api
   ____    __
  / __/___/ /  ___
 / _// __/ _ \/ _ \
/___/\__/_//_/\___/ v4.10.2
High performance, minimalist Go web framework
https://echo.labstack.com
____________________________________O/_______
                                    O\
⇨ http server started on 127.0.0.1:9090
```
```
The answer is to use the --binding cli argument to listen on all addresses

./singularity run api --bind "0.0.0.0:9090"

   ____    __
  / __/___/ /  ___
 / _// __/ _ \/ _ \
/___/\__/_//_/\___/ v4.10.2
High performance, minimalist Go web framework
https://echo.labstack.com
____________________________________O/_______
                                    O\
⇨ http server started on [::]:9090
```

Herein lies the confusion:
- Using Google suggests that go echo server does not use a configuration file and the IP address and port numbers must be changed in the source:

```
package main

import (
	"github.com/labstack/echo/v4"
	"net/http"
)

func main() {
	e := echo.New()

	// Define routes
	e.GET("/", func(c echo.Context) error {
		return c.String(http.StatusOK, "Hello, Echo!")
	})

	// Start the server
	e.Start(":8080")
}
```

- But trawling the singularity source reveals these places where the IP and port are specified

```
./docs/en/cli-reference/run/api.md:   --bind value  Bind address for the API server (default: "127.0.0.1:9090")
./docs/zh/cli-reference/run/api.md:   --bind value  API 服务器的绑定地址 (默认值: "127.0.0.1:9090")
./docs/jp/cli-reference/run/api.md:   --bind value  APIサーバーのバインドアドレス（デフォルト: "127.0.0.1:9090"）
./docs/kr/cli-reference/run/api.md:   --bind value  API 서버를 위한 바인드 주소 (기본값: "127.0.0.1:9090")
./docs/swagger/swagger.yaml:host: localhost:9090
./docs/swagger/docs.go: Host:             "localhost:9090",
./docs/swagger/swagger.json:    "host": "localhost:9090",
./dashboard/README.md:This stands up the backend server on [http://localhost:9090](http://localhost:9090)
./client/swagger/http/singularity_api_client.go:        DefaultHost string = "localhost:9090"
./client/client_test.go:                        Bind:       "127.0.0.1:9090",
./client/client_test.go:                client := httpclient.NewHTTPClient(http.DefaultClient, "http://127.0.0.1:9090")
./singularity.go:// @host localhost:9090
./go.sum:golang.org/x/lint v0.0.0-20190909230951-414d861bb4ac/go.mod h1:6SW0HCj/g11FgYtHlgUYUwCkIfeOF89ocIRzGO/8vkc=
./go.sum:gopkg.in/check.v1 v1.0.0-20190902080502-41f04d3bba15/go.mod h1:Co6ibVJAznAaIkqp8huTwlJQCZ016jof/cbN4VW5Yz0=
./docker-compose.yml:      - 9090:9090
```


- the file  **singularity_api_client.go** appears to be a good candidate

```
        // DefaultHost is the default Host
        // found in Meta (info) section of spec file
        DefaultHost string = "localhost:9090"
        // DefaultBasePath is the default BasePath
        // found in Meta (info) section of spec file
        DefaultBasePath string = "/api"
```

However, where is the "spec" file? I found none

The solution to the problem is NOT revealed with

`./singularity -h`

```
BUT this does help:

./singularity run api -h
NAME:
   singularity run api - Run the singularity API

USAGE:
   singularity run api [command options] [arguments...]

OPTIONS:
   --bind value  Bind address for the API server (default: "127.0.0.1:9090")
   --help, -h    show help
```

**Summary:**
- how to change the internet facing ip address for go echo webserver is not obvious at all
- please put into the main install documentation
- much time will be saved for the user community
- using 0.0.0.0 might not be the best answer for security reasons (possibly actual IP addresses)

**Comment by distora-w3** [comment]
Additional items to set  paths in .bashrc

The following will help speed up installation by alerting the need to have singularity binaries in the path
`export PATH=$PATH:/usr/local/go/bin:$(/usr/local/go/bin/go env GOPATH)/bin:**$HOME/singularity**`

The documentation on this page suggests that the database is stored in **$HOME/.singularity**  see https://data-programs.gitbook.io/singularity/data-preparation/create-a-dataset

Item #90  causes a conflict with this specification 
`export DATABASE_CONNECTION_STRING=sqlite:$HOME/singularity.db`

Actually, to follow the documentation we need to do the following:
`mkdir $HOME/.singularity
export DATABASE_CONNECTION_STRING=sqlite:$HOME/.singularity/singularity.db`

**Comment by xinaxu** [comment]
@distora-w3 Your comments about the API binding makes sense, we will improve the documentation next week.
For the database connection string, the gitbook document is not up to date - it's for the version that was 2 months ago. We're working on reorganizing the gitbook content for easier consumption. For now please stick with the help page from the CLI, i.e. in `singularity -h`, you will see the default database is using the `singularity.db` in the current directory, not the HOME directory any more. That's because not all platform has a HOME folder so we're moving away from relying on this.

Also, for your comments about setting up binding, firewall, environment variables. We will improve them to some extent - likely link to external resources instead of listing all the steps for how to setup firewall and environment variables on Windows, MacOS, Linux, etc. We don't want to jump into rabbit hole of how to setup firewall in different versions of Windows, or different firewall solution in Linux.

@celine3650 meanwhile I think we need to think about how to present different gitbook content to users. i.e. skip some obvious content for highly technical user and show more details for non technical users, including understanding where did they get block (probably with google analytics) and their feedback. @distora-w3 choose to write down his frustration above but other users may just leave without any feedback

**Comment by distora-w3** [comment]
Hello @xinaxu I agree with you that certain items like how to configure firewall is out of scope.
**BUT to know if the go echo server is up and correctly serving pages is in scope.** Perhaps some of these items can be in a "trouble shooting" section? 

For example, I had no idea that binding is local only.  (This is also documented on external go echo sites) Therefore the issue is "how do I know that I have a problem?". We can, with the singularity documentation, help other users narrow down the search space.

**Please note.** I am not making a complaint or showing frustration or making criticisms. Every project in this ecosystem is complex with many dependencies and challenges. I deliberately joined the V2 testing to represent the smaller SPs community. The mistakes I make are probably similar to the mistakes that other newbies will make.

I value the fact that you are taking on board my feedback. Thank you  :)

**Comment by xinaxu** [comment]
> The installation page has a section for "get started or prerequisites or minimal requirements."

This is now addressed by binary releases for all different platforms
https://github.com/data-preservation-programs/singularity/releases

> Creating awareness of the richness of singularity v2 with many options available to improve performance and allow the user to find these options and settings.

Tracked in #304 

> The answer is to use the --binding cli argument to listen on all addresses

The latest version has binding address default to all network address
