### ISSUE TITLE
[Bug]: $HOME/.singularity

### ISSUE THREAD

**Issue by distora-w3** [data-preservation-programs/singularity#163]
### Description

```text
ISSUE: SQLlite database not created in $HOME/.singularity

DESCRIPTION
- this is either a documentation problem (added note to #150)
- or installation process is not checking for $HOME/.singularity

ACTIONS
- IF this is a documentation issue please see issue #150 comment and first section of https://data-programs.gitbook.io/singularity/data-preparation/create-a-dataset
- ELSE "singularity admin init" requires logic or has bug

EXPECTED OUTCOME
- by default databases, config, working files, cache etc are stored in $HOME/.singularity
- ENV var can be set to override default location

RATIONALE
- $HOME/.singularity is a good convention for the reason that Lotus uses $HOME/.lotus and Boost uses $HOME/.boost
```

### Steps to Reproduce

1. Require vanilla installation
2. Check for the existence of and unset if required
`export DATABASE_CONNECTION_STRING=sqlite:$HOME/singularity.db  (specified in #90 )`
3. run
`singularity admin init`
4. singularity.db is created in $HOME
`167936 Aug  4 08:57 singularity.db`

### Version

singularity v0.2.47-b5613c3

### Operating System

Linux

### Database Backend

SQLite

**Comment by xinaxu** [comment]
I have modified the instruction in #90 and removed information about creating the database in home folder.
