### ISSUE TITLE
[Bug]: Creating dataset with name `*` - dataset name becomes "api" 

### ISSUE THREAD

**Issue by jcace** [data-preservation-programs/singularity#175]
### Description

```text
Trying to create a dataset named `*` will create a dataset named `api` instead. We should probably sanitize the input just to make sure the user can't break anything with some weird names.
```

### Steps to Reproduce

1. Run below commands
```
singularity dataset create *
```
2. View the output - dataset named `api` will be created. 
<img width="1063" alt="Screenshot 2023-08-07 at 10 40 46 AM" src="https://github.com/data-preservation-programs/singularity/assets/12418265/2a825009-5800-4aa2-8d11-cd4b80a36ec6">

### Version

singularity v0.2.47-91f29eb

### Operating System

Linux

### Database Backend

SQLite

**Comment by xinaxu** [comment]
I think this is caused by your shell - for most shells, i.e. bash, `*` will be translated to all files in the current directory. You can escape this behavior by quoting it `'*'`
