### ISSUE TITLE
Naming Item/ItemPart/Chunk

### ISSUE THREAD

**Issue by hannahhoward** [data-preservation-programs/singularity#186]
Referencing @willscott @elijaharita discussion in #159 , as well as some informal conversations I've had offline, the names Item, ItemPart, and Chunk can be quite confusing. They're very generic, and applied in different ways. I'd love to move them closer to the domain objects we have in the original Motion/Singularity domain model, or at least names that have more obvious meaning for new devs.

Based on working with the code for a few weeks, and having a pretty clear mental model for what each is doing, I would suggest the following:

Item -> Blob
ItemPart -> BlobRange
Chunk -> CarBlobManifest

A big name refactor can be a bit disruptive but my belief is we should do this before we hit 2.0 final.

Also happy to take alternative suggestions.

cc: @xinaxu @willscott @elijaharita

**Comment by hannahhoward** [comment]
@xinaxu how do you feel about this? If you're ok with it, I'd go ahead and do it.

**Comment by xinaxu** [comment]
> Item -> Blob

If I just look at in Singularity' context, a more proper name to Item is File. Blob stands for binary large object which is fine too, but if you look at model.Item, it has directory_id, which indicates it is a directory entry, hence a file.

> ItemPart -> BlobRange

Same as above, FileRange would be better to me

> Chunk -> CarBlobManifest

The chunk is essentially a grouping of ItemParts which will be picked up by the dataset worker. To me, BlobRangeGroup, BlobRangePack is better

**Comment by elijaharita** [comment]
File and FileRange makes sense, i agree

however, I'm not sure I understand why CarXManifest isn't suitable. aren't the contents of this object going to be converted into a single car file? in that case i think it would make the most sense to have car in the name to make it clear what it's going to be used for. unless i am misunderstanding and these objects are not processed 1:1 into cars?

**Comment by xinaxu** [comment]
Looked up the dictionary and agreed with CarXManifest.
Should we just call it CarManifest?

**Comment by elijaharita** [comment]
yeah, I also thought just calling it CarManifest makes sense!

**Comment by elijaharita** [comment]
i could take on this renaming issue if you're cool with that

**Comment by xinaxu** [comment]
Yes, please. Hopefully it won't be too much of work - some table names are inside string literals.

**Comment by xinaxu** [comment]
There is also
https://github.com/data-preservation-programs/singularity/blob/main/docs/en/technical-architecture/data-preparation.md
@hannahhoward knows how to generate that diagram.
Also
I can help with regenerating this diagram if you had trouble installing that schemacrawler https://github.com/data-preservation-programs/singularity/blob/7e8e8cccdd2f7df4fc773516215a8da4e900df47/Makefile#L18

**Comment by elijaharita** [comment]
how should we handle db migration for this change? should it be built into the program and run automatically, or would it make sense to just write a script and distribute separately? i don't know how many active users singularity v2 has at the moment.

**Comment by elijaharita** [comment]
another question - the pack function takes a single chunk id and returns an array of cars. in what situation can multiple cars be created from a single chunk?

**Comment by elijaharita** [comment]
ah ok, that's interesting. in my own head CarManifest made sense because i had assumed a 1:1 mapping with Cars. @hannahhoward what's your opinion on this?

**Comment by hannahhoward** [comment]
Yea, I guess we could call it a PackingManifest to clarify it goes in multiple CARs maybe

**Comment by elijaharita** [comment]
that makes more sense to me, i like it

**Comment by hannahhoward** [comment]
personally I would go with Packing, cause Pack is usually a verb, but either way.

**Comment by elijaharita** [comment]
i thought about that as well. PackingManifest is really descriptive but also a bit long

what about just `PackJob`? "[verb] job" is a standard usage. it would make a lot of sense to me especially since it contains working information like its state and worker id

**Comment by xinaxu** [comment]
I'd also prefer PackJob over Packmanifest
