### ISSUE TITLE
Dataset should have a max replication factor / Deal sending checks

### ISSUE THREAD

**Issue by marshyonline** [data-preservation-programs/singularity#209]
### What is the problem you're trying to solve?

Singularity v1 has the ability to set a max replication factor - allowing you to store no more than X copies of all CID's in a set.
This feature is missing in v2

v2 is also missing all checks on whether or not we are sending the same CID to a storage provider that already has a CID proposed or active, allowing for duplicate deals to be sent and sealed. 

Not all providers use the pull method for deals and it is essential that these checks and limits are in place for both the manual deals, scheduled deals and pull API deals. 
The only way we should be able to override this check, is to --force when sending deals. 

### Describe the workaround you currently have

I don't have any workaround

### Describe the feature you'd like

I would like singularity to match v1 as close to 1:1 as possible.

**Comment by xinaxu** [comment]
@hannahhoward @marshyonline 
For motion, I remember there is a requirement to define number of replicas. Hence I think this issue may be relevant for motion MVP. Could you confirm?
This number of replica restriction is only applicable to deal making with N storage providers but only allows M number of replicas where N > M.

**Comment by masih** [comment]
I think that's right, in that, for Motion we need to be able to specify replica count. For the MVP it is fine to specify that indirectly as a function of a given set of providers where replication would effectively equal the number of unique providers configured.
