### ISSUE TITLE
[Bug]: `singularity tool extract-car` giving `ipld could not find` error

### ISSUE THREAD

**Issue by jcace** [data-preservation-programs/singularity#210]
### Description

```text
See repro steps below. I'm unable to extract inline-prep'd carfiles and get back the original directory structure as it always produces an `ipld could not find <cid>` error.
```

### Steps to Reproduce

1. Install singularity 
2. Make some sample data using this script (ex: `./sing-sample-data.sh /srv/singularity/in`)
https://gist.github.com/jcace/f811078f5cc110425cb317b3b87da654
3. `./singularity dataset create dataset_name`
4. `./singularity datasource add local dataset_name /srv/singularity/in`
5. `./singularity run dataset-worker --exit-on-error --exit-on-complete`
6. `./singularity datasource daggen 1`

... wait for it to finish ...

8. Grab the piece cids for the 2 carfiles it produced i.e:
```bash
./singularity datasource inspect chunkdetail 1 | head -n 15 
./singularity datasource inspect chunkdetail 2 | head -n 15
```

Gave the piece cids:
- baga6ea4seaqhd2lxgalclfzruywctmma4sai3tigjmbnh4ahx2fhk22fbxoimgi
- baga6ea4seaqcbp33kmi5peejpjgrk4dyrdxdhwe4exodhnjoxcqe44svmmi2eli

7. `singularity run content-provider`
8. download the pieces from the content provider:
```bash
curl localhost:7777/piece/baga6ea4seaqhd2lxgalclfzruywctmma4sai3tigjmbnh4ahx2fhk22fbxoimgi --output /srv/singularity/test/baga6ea4seaqhd2lxgalclfzruywctmma4sai3tigjmbnh4ahx2fhk22fbxoimgi.car 

curl localhost:7777/piece/baga6ea4seaqcbp33kmi5peejpjgrk4dyrdxdhwe4exodhnjoxcqe44svmmi2eli --output /srv/singularity/test/baga6ea4seaqcbp33kmi5peejpjgrk4dyrdxdhwe4exodhnjoxcqe44svmmi2eli.car
```

9. Grab the root cid for the dag 
`./singularity datasource inspect path 1`

produces: `bafybeicfseigqikarzsknxtmy2snylailkmi65xzhld7l3qyqfmhiwr6uy`

10. Try to extract from the cars downloaded
`./singularity tool extract-car --input-dir /srv/singularity/test/ --output /srv/singularity/test-out --cid bafybeicfseigqikarzsknxtmy2snylailkmi65xzhld7l3qyqfmhiwr6uy`

Produces error:
```
2023/08/15 23:50:54 failed to get node for CID bafybeicfseigqikarzsknxtmy2snylailkmi65xzhld7l3qyqfmhiwr6uy: ipld: could not find bafybeicfseigqikarzsknxtmy2snylailkmi65xzhld7l3qyqfmhiwr6uy 
```

### Version

v0.2.47-1f0d416

### Operating System

Linux

### Database Backend

SQLite

**Comment by xinaxu** [comment]
Closing as not reproducible
