### ISSUE TITLE
Discuss the future of alternative client APIs

### ISSUE THREAD

**Issue by masih** [data-preservation-programs/singularity#223]
The repo currently offers two flavours of client library APIs:
1. swagger generated HTTP client library
2. [hand crafted HTTP client libray](https://github.com/data-preservation-programs/singularity/tree/0b8005d3068dfd78bb4eea84316ee12b2d58f7a8/client/http)

The hand-crafted API currently supports ceating data sets, creating local source, get item and push item. So far all of these operations have a direct corresponding HTTP call, which can also be made using the swagger auto generated client API.

Going forward, we most likely do not want to maintain 2 sets of client libraries _if_ the functionality across them is the same. At the very least we want to reduce duplication between them.

Considering the breadth of HTTP APIs exposed by singularity and the code maintenance cost across the two versions, discuss:
* what future we envision for the hand crafted HTTP?
* what is the rationale for having both?

Related comments across PRs:
* https://github.com/filecoin-project/motion/pull/29#discussion_r1278314080
* https://github.com/data-preservation-programs/singularity/pull/94#issuecomment-1653994236

**Comment by hannahhoward** [comment]
Truthfully I'm not passionate about which API we use, but the path to Motion M2 is set and I'd like to just focus on delivery. Once it's in, I'm happy to switch to Swagger and remove the client APIs.

**Comment by masih** [comment]
Thanks hannah, I'd love to pick your brain on this further

**Comment by xinaxu** [comment]
Currently the swagger client have been unit tested and are being integrated with motion.
