### ISSUE TITLE
[Bug]: Key management / docs for keys

### ISSUE THREAD

**Issue by distora-w3** [data-preservation-programs/singularity#230]
### Description

```text
Issue [1] : Review key management best practices and display via cli
- probably not wise to display private key
- once key is added and tested only delete should be possible  ( I see the ability to export as being dangerous)

Issue [2] : Wallet balance needed
- there are two values
- FIL
- Datacap

Issue [3] : Documentation needed
- where to get keys, how to set up keys
- difference datacap / standard
- remote key and peer needs and explanation with example
```

### Steps to Reproduce

Run command 
singularity wallet list
```
2023-08-24T09:35:12.189Z        INFO    database        database/connstring_cgo.go:26   Opening sqlite database (cgo version)
ID         Address                                    PrivateKey                                                                                                                                                        RemotePeer
f02130217  f1nlhouj6cwctb4lijgh4tej7hhvdlwc5oc3byp5y  7b2254........................................................................................2553d227d
```

I don't see the value of displaying the private key. A security concern?

For reference:
- Lotus keep keys in a folder ~/.lotus/keystore
- file names are base32 encoded
- admin has the ability to scp files from server to server  (and remove)

### Version

v0.2.47-1f0d416-dirty

### Operating System

Linux

### Database Backend

SQLite

**Comment by distora-w3** [comment]
[Issue 4] Also, it would be good to list the datasets associated with a wallet

```
singularity wallet list

Dataset                ID                Address        PrivateKey       RemotePeer
[Dataset name]    f02130217  f1n.....5y        7b2...2223
```

**Comment by xinaxu** [comment]
> Issue [1] : Review key management best practices and display via cli

addressed in https://github.com/data-preservation-programs/singularity/blob/f2ad59fff6a7a0a4a87d03b0830c5b3ce3c0afc0/model/replication.go#L140

> Issue [2] : Wallet balance needed

Singularity is not an all-in-one software that displays everything. You should utilize `lotus` for this purpose.

> Issue [3] : Documentation needed

We will be working on documentation, we just don't yet have resources for that yet. Once the new refactor change is released. Let's talk about how we can improve documentations. - Could probably use some of your time?

> [Issue 4] Also, it would be good to list the datasets associated with a wallet

Addressed in the refactroing

**Comment by xinaxu** [comment]
> [Issue 2] Depends on the use case. The user might not have access to lotus. Also at some point lack of wallet balance in FIL or Datacap will cause a deal to fail. (From memory, not all tools display datacap on wallet list)

Again, Singularity is not going to implement all features that's already available with other tools. The user should manage wallet balance, market balance, datacap with other tools. You may raise it as a feature request, though it will have a lower priority as the focus right now is to ship features that are not available from other tools. Those info are nice to have but not a must for shipping the next milestone.

> [Issue 3] Can we document in raw form as we go along or at least make them easy to find or tagged?

I would suggest
1. Create a separate issue for a different ask, i.e. in this case, hiding private key and wallet CLI documentation are two 
2. Put it into the discussion board
3. If it's simple, you can create a pull request and help improve the documentation.
