### ISSUE TITLE
Deal Making Scheduler

### ISSUE THREAD

**Issue by xinaxu** [data-preservation-programs/singularity#25]
## Description

Allow pushing deals to specific storage provider with certain restriction and schedule
* Boost specific options - httpheader, ipni announcement, URL to download CAR file
* Deal proposal options - duration, price, verified, keepunsealed
* Scheduling options - cron pattern, number per trigger, total number of deals, max pending deals
* Others from user asks - notes, allowedCIDlist

**Comment by marshyonline** [comment]
@xinaxu - i can only really see one key option missing from deal-making and that is the ability to specify the max number of replications per Piece CID - this is key for us to make sure we don't get more than X copies of a single CID

**Comment by xinaxu** [comment]
That will be part of story for pull mode - I haven't created backlog for them but it will be looked at very soon.

**Comment by marshyonline** [comment]
> That will be part of story for pull mode - I haven't created backlog for them but it will be looked at very soon.

I really think this should be an overall setting in a way, regardless of the push or pulling of deals
If I want a max of 5 copies of a dataset, I should be able to set this for either mode.
This will make maintaining replication super easy, else we are going to need some other way to check how many times a CID has been sealed.

**Comment by marshyonline** [comment]
I also can't see any limits on stopping the same CIDs from being proposed/sealed by the same provider more than once.

This is a big one and a MUST, we don't want another repeat of issues from v1 where LDN had massive dupe data issues. 
The only way you should be able to override this is with a single manual deal, the scheduler should never send the same deal to the same provider more than once.
