### ISSUE TITLE
Collect feedback from singularity V2 testers

### ISSUE THREAD

**Issue by celine3650** [data-preservation-programs/singularity#252]

**Comment by celine3650** [comment]
https://docs.google.com/presentation/d/1DY1dNUICkfVt7EHz3kZ1-TEJh8XVQXu0GTMq00V5wLM/edit

**Comment by celine3650** [comment]
Greater heat, Solana will start to test deal making V2 in Oct. Move it to backlog for now.

**Comment by celine3650** [comment]
Follow up with Greater Heat in sprint 9.

**Comment by celine3650** [comment]
The goal of this is to include bug triaging, performance improvement, and small iterations based on user feedback to maintain and enhance v2.

**Comment by xmcai2016** [comment]
@celine3650 can we close this one?
