### ISSUE TITLE
Perpetual Scheduling

### ISSUE THREAD

**Issue by hannahhoward** [data-preservation-programs/singularity#254]
For motion, we essentially want a perpetual schedule — one that will simply push each new packed car file to the provider in perpetuity. 

I see that Singularity has essentially has one-off schedules and chron schedules, but unless I’m reading the code wrong (https://github.com/data-preservation-programs/singularity/blob/main/service/dealpusher/dealpusher.go#L288-L298), it would appear once all car files in a dataset have deals that are in process (Proposed/Published/Active), the schedule is marked completed, an no further deals are made from that schedule.

Possible approaches to solving this issue:
- Add an attribute to Cron Schedules to make them "perpetual" -- as in they never get marked completed, even if there are no cars in a dataset that don't have proposed deals
- When creating a schedule, as an attribute on the model, allow specifying an HTTP endpoint for a callback that's called when a schedule is completed. 
   - Why? 
      - This would allow motion to listen for said callback and make new schedules on demand.
      - As an optimization, allow "restarting" schedules -- i.e. to force a schedule out of Completed, to conserve database space
      
 @xinaxu if you can given guidance on preferred implementation, we can implement it. I kind of like the second option, cause it's a somewhat smaller change to Singularity's design, and gives Motion more control.

**Comment by xinaxu** [comment]
fixed in #256
