### ISSUE TITLE
Dashboard / dataset explorer

### ISSUE THREAD

**Issue by xinaxu** [data-preservation-programs/singularity#26]

**Comment by xinaxu** [comment]
Feedback from Pauli
In an ideal world, for singularity V2, there would be dataset page where I can click in to find the following info:
* find all the references, dag, deal cid, piece cid etc  (just list them all, the community seems to confuse them)
* list the replicated SPs with a status eg 100% or green or orange for some deals that have not made it or red for all that have failed. The error message from the SP should also be reported. eg, price too low or file size too low
* for each SP list the sector that contains the deal (means talking to Boost)
* finally the ability to re-queue or re-run the replication process to bring all the SP status up to 100% (green)

**Comment by celine3650** [comment]
This is the current Figma. https://www.figma.com/file/mRg6izXLreoZw375ZCvPzD/Draft-v1---Data-onboarding-Wireframes?type=design&node-id=0-1&mode=design&t=TRSPN7fZ1vM7kce7-0
