### ISSUE TITLE
[Bug]: --url-template is not obvious in cli singularity deal send-manual

### ISSUE THREAD

**Issue by distora-w3** [data-preservation-programs/singularity#308]
### Description

```text
Two items:
[item 1] The word "template" has many connotations and can cause confusion. The expectation is variability, options... or even pattern-matching

Alternative, (and should be self documenting)

--car-path
--car-url
--car-source-file
--http-car

[item 2] Include additional example command in -h output
Reason: I struggled to make the command work when there was an error. Setting verbose was not obvious, I saw something similar to this in Slack

singularity -json --verbose deal send-manual --client fxxxx \
    --provider fxxxx --piece-cid baga6..... --file-size 1616 --piece-size 32GiB \
    --url-template "http://45.32.178.42/baga6......car"
```

### Steps to Reproduce

The example in 
`singularity deal send-manual -h`

We see
` --url-template value  URL template with PIECE_CID placeholder for boost to fetch the CAR file, i.e. http://127.0.0.1/piece/{PIECE_CID}.car`

### Version

0.4.0

### Operating System

Linux

### Database Backend

SQLite

**Comment by xinaxu** [comment]
> item 1

In boost the flag for the same flag is
```
 --http-url value                               http url to CAR file
```

>item 2
It is hard to get it right. We expect the user to be already familiar with those concept using lotus or boost CLI. Is below example enough?
https://github.com/data-preservation-programs/singularity/blob/8b2849ef6ebd53f584e3bc0ddf93ed9563248727/cmd/deal/send-manual.go#L22
