### ISSUE TITLE
Replication Factor for Preparation/Schedule

### ISSUE THREAD

**Issue by hannahhoward** [data-preservation-programs/singularity#315]
# What

As a user of singularity, for a given preparation, and pool of Providers, I want to be able to have every CAR file in the preparation replicated N times, across any of the SPs in the pool, and no more

Currently, a preparation has schedules, where each schedule has a single provider. Absent other limits, the schedule will make a deal for every CAR file in the preparation.

But there a number of scenarios where I want a preparation to have a large pool of providers, but only require each CAR to get replicated a few times.

It seems like the simplest way to do this would be to add a "ReplicationFactor" attribute to a preparation and then have schedules simply ignore car files that already hit the replication factor. This would essentially allow several schedules to reach the replication factor on a first-come, first-served basis.

An alternate strategy would be to add an additional "multi-provider schedule" which would encompass all this logic, but that sounds complciated.

**Comment by xinaxu** [comment]
Similar ask in #209 

I am planning to introduce a policy concept that defines certain constraints, including max number of replicas for a preparation.

When do you need this by?

**Comment by hannahhoward** [comment]
@celine3650 for feedback on that.

"Replication Factor" was an original config we defined for Motion MVP (later renamed Alpha). That said, I don't see it being a major issue if we don't ship it till Beta, since I expect ISVs to only be testing in alpha with a couple SPs.

**Comment by hannahhoward** [comment]
On the other hand, if we could get this done by end of next week -- 9/21 -- we can incorporate it in motion Alpha which would be nice. Depending on your other priorities, this would be great to have done.

**Comment by xinaxu** [comment]
9/21 may be too tight. I would like to think about a generic polcy system design so it can be extensible to other types of policy.

**Comment by xinaxu** [comment]
For now, let's make this a global variable
