### ISSUE TITLE
Retrieval Optimization for Singularity + Filecoin

### ISSUE THREAD

**Issue by hannahhoward** [data-preservation-programs/singularity#366]
Currently, retrievial through singularity is implemented through a read seeker abstraction. Since the io.ReadSeeker abstraction does not know about the over range parameters of the incoming HTTP request to Singularity, when serving a file that is not in the local storage, each call to the io.Reader.Read method is implemented by making a seperate filecoin retrieval for the exact range parameters of that individual read operation. 

Under the hood, the implementation of `http.ServeContent` that we employ uses `io.CopyN`, which in turn executes read operations in the neigborhood of 32K, and extremely small request. This turns read requests into 32k Filecoin retrievals, which is obviously extremely inefficient.

The proposed optimization here is as follows:
- parse the HTTP Range header -- this code to do this is surprisingly not easily available but there are examples in the HTTP ServeContent implementation (https://cs.opensource.google/go/go/+/refs/tags/go1.21.1:src/net/http/fs.go;l=887) and then I found a good example here (https://github.com/gotd/contrib/blob/v0.19.0/http_range/range.go).
- one caveat, you need to get the size of the overall file record first to parse ranges correctly. (so read the File DB record first)
- Now you can pass your ranges to your read seeker, and change it's implementation as follows:
   - on first read, check if your current offset lies within one of the ranges
      - if so, make a pipe reader
      - start a go routine and  execute a range request to the filecoin retriever for the current position until the end of the current HTTP range or the current FileRange, whichever comes first -- pass it the pipe writer for a destination (sidebar: this will be easier to implement if you modify the `FilecoinRetriever` to return an `io.Reader`, then you don't need the pipe+goroutine)
      - now save the reader on the struct and use its read method to serve the current read operation
      - for subsequent read operations if an existing reader is already present, read from it (remove it from the struct if you hit EOF)
      - otherwise follow the operations above to execute another larger range request
      - wipe the saved reader whenever there's a Seek and cancel the HTTP request in progress.

Note: there is a lot of similarity with https://github.com/filecoin-project/motion/issues/143 and you may want to share code

**Comment by gammazero** [comment]
There might be a simpler way to do this. If the `ReadSeeker` also implements `io.WriterTo` then when `io.CopyN` in `http.ServeContent` is called, the Readeeker's `WriteTo` is called and the entire requested size can be written directly to the `Writer`. No need to track the current range, start a goroutine, create a pipe in order to facilitate writing little chunks to a default `io.Copy` buffer.
