### ISSUE TITLE
[Bug]: Some parameters in `deal schedule` are not taking effect

### ISSUE THREAD

**Issue by jyma** [data-preservation-programs/singularity#367]
### Description

```text
1.`--allowed-piece-cid-file` and `--allowed-piece-cid` cannot send deals restricted to specific piece IDs.
2.`--number` cannot limit the number of deals sent.
```

### Steps to Reproduce

1. Run below commands
```
singularity run deal-pusher
```
2. `singularity deal schedule create --preparation 1 --provider f0888866 --duration 12720h --start-delay 192h --allowed-piece-cid-file /home/zizi/owndc/1.list --number 1`
3. `singularity deal schedule create --preparation 1 --provider f02228866 --duration 12720h --start-delay 192h --allowed-piece-cid baga6ea4seaqpsluj6pxxodyuqhiopw55mzsv5dmkzibzmfyv7j6ik5fmawqgeeq --number 1`
4. cannot send deals restricted to specific piece IDs and cannot limit the number of deals sent.

### Version

0.5.0

### Operating System

Linux

### Database Backend

SQLite

**Comment by xinaxu** [comment]
> `--number` cannot limit the number of deals sent.

You're using the wrong argument. You need to use `--total-number`.
