### ISSUE TITLE
High bandwidth consumption with low preparation speed

### ISSUE THREAD

**Issue by xinaxu** [data-preservation-programs/singularity#375]
>Are there people around here who have done a succesfull inline prep of a dataset?  I am running some prep jobs for testing for a few weeks now but the amount of bandwidth used does not match the things "build" in any way. For example a dataset of 60 TB is downloading now for days @20 Gbit/s. But this should finish in a couple of hours?
Technically at this speed it should finish in a little over 7 hours. 
 any clue what could be happening here?

>Version is the latest master of yesterday. Dataset’s i have tried are terrafusion, African sounds and nasanex. All same result

**Comment by cryptowhizzard** [comment]
To re-iterate:

It seems ( when we look at the car files ) that there is duplication going on with the files packed many times in a .car file. This causes the slow speed I guess.

**Comment by cryptowhizzard** [comment]
> @cryptowhizzard could you confirm if this is fixed?

Yup, Fixed.

Thanks!
