### ISSUE TITLE
[Bug]: failed to create deal: Error 1048 (23000): Column 'last_verified_at' cannot be null

### ISSUE THREAD

**Issue by cryptowhizzard** [data-preservation-programs/singularity#399]
### Description

```text
failed to create deal: Error 1048 (23000): Column 'last_verified_at' cannot be null

Seems someone forgot to add this to the upgrade script.

Running latest master singularity v0.5.3-623947d
```

### Steps to Reproduce

1. Run below commands
```
singularity ...
```
2. Go to '....'
3. See error

### Version

singularity v0.5.3-623947d

### Operating System

Linux

### Database Backend

MySQL

**Comment by xinaxu** [comment]
Have you run `singularity admin init` after upgrading the version?

**Comment by cryptowhizzard** [comment]
No, this was not clear to me that i needed to do that.

**Comment by xinaxu** [comment]
I'm going to put it to the help page of
`singularity -h`
`singularity admin init -h`
