### ISSUE TITLE
[Bug][Docs]: Database Diagram does not reflect the current schema

### ISSUE THREAD

**Issue by SethDocherty** [data-preservation-programs/singularity#437]
### Description

After reviewing the [database-diagram](https://github.com/data-preservation-programs/singularity/blob/main/docs/database-diagram.svg), I noticed that it's out of date and does not match the current database schema that is generated when running `singularity admin init`.

It would be beneficial to have the latest update as our team is looking into developing an ETL pipeline, offloading finished tasks from our in-line prep worker instances to our hosting server instance for deal-making with SPs.

### Steps to Reproduce

Per the notes in the bottom right corner, this diagram was last generated in 2023-07-27.

### Version

Latest

### Operating System

Linux

### Database Backend

SQLite

**Comment by parkan** [comment]
you can always regenerate this by downloading openjre + sdkman + installing schemacrawler via sdkman and running `make diagram` (with the sdkman path in your env)

I've opened a PR with the latest diagram above
