### ISSUE TITLE
Data source / Folder structure

### ISSUE THREAD

**Issue by xinaxu** [data-preservation-programs/singularity#68]
## Description

By default, the folder structure will not be exported to CAR file because
* Singularity does not know whether the user wants the store the folder structure, especially if encryption is enabled.
* Singualrtiy does not know when the final state has reached, especially when data source rescan is enabled.

Singualrity willl offer a utility to trigger the folder structure generation that exports folder structure to a CAR file

## Acceptance Criteria
Run `singularity datasource daggen` to trigger folder structure dag generation which will export to a new CAR file. The dataset worker will pick up the request and process the request.

* [Once #15 is done] The user will be able to retrieve the whole directory or a sub directory of a dataset using the rootCID of the dataset and any subpath

**Comment by hannahhoward** [comment]
@willscott @xinaxu I am not sure we really need this for retrieval for Motion MVP. Here's why:

My proposal is that each Motion blob is a unique Dataset, with a single Source, with a single root Directory, with a single Item that is the bytes of the blob. (alternatively each motion blob is a separate source).

Given this setup, the Item + ItemParts + Chunks  database should be sufficient to execute a retrieval. Essentially, you simply execute a retrieval for each item part, which we know to be in a single car file and which we have the root CID for.
