### ISSUE TITLE
Unit test deal maker service

### ISSUE THREAD

**Issue by hannahhoward** [data-preservation-programs/singularity#76]
Service: https://github.com/data-preservation-programs/singularity/blob/main/service/dealmaker/dealmaker.go

Seems like we could take two approaches here:
1. Integration test with the DealMaker and WalletChooser from `replication`
2. Since those two modules are unit tested, convert their references in DealMakerService to interfaces and true unit test

Probably use SQLite to generate an initial database

Goal is to verify correct behavior based on state of schedule in the DB

@xinaxu thoughts? is this something we should be testing now? are other services (datasetworker, dealstatus) higher priority to test

**Comment by xinaxu** [comment]
Thanks. The deal maker part is still work in progress. I finish most of the code the week before last week but did not get a chance to add tests here. 
To me the priority is
1. basic test for deal making scheduler - so we can hand it over to external testers
2. more thorough test for dataset preparation 
3. more thorough test for deal making scheduler

**Comment by hannahhoward** [comment]
this is great @kylehuntsman this is something you can start on, or at least start familiarizing yourself with.

**Comment by hannahhoward** [comment]
may still be block on getting you access.

**Comment by davidd8** [comment]
@dkkapur can you add @kylehuntsman to this project or @data-preservation-programs/bedrock?

**Comment by anjor** [comment]
@kylehuntsman has been added.
<img width="675" alt="Screenshot 2023-07-19 at 7 12 46 PM" src="https://github.com/data-preservation-programs/singularity/assets/1911631/79a8e27f-d9db-465a-89e3-5b70d21a4f88">

**Comment by xinaxu** [comment]
Closing as the test will be tracked in other issues
