### ISSUE TITLE
Basic dataset preparation using local file system with Linux and SQLite

### ISSUE THREAD

**Issue by xinaxu** [data-preservation-programs/singularity#90]
## Note
* Enable debug log using `export GOLOG_LOG_LEVEL=debug` if the default error log is not enough to tell what's the issue
* All bugs please create an issue for us to triage https://github.com/data-preservation-programs/singularity/issues. Then reference the bug# in the test issue.
* Mark relevant columns to "Tested" in https://github.com/orgs/data-preservation-programs/projects/4

## Installation from source
1. Install go version 1.19+
```
wget -c https://golang.org/dl/go1.19.7.linux-amd64.tar.gz -O - \
    | sudo tar -xz -C /usr/local
```
2. Make sure you have `~/go/bin` in your `$PATH`
```
echo 'export PATH=$PATH:/usr/local/go/bin:$(/usr/local/go/bin/go env GOPATH)/bin' \
    >> ~/.bashrc && source ~/.bashrc
```
3. Install Singularity
```
git clone https://github.com/data-preservation-programs/singularity.git
cd singularity
make build # or go build -o singularity .
./singularity -h
```
4. Upgrade Singularity
```
git pull
make build # or go build -o singularity .
./singularity -h
```
5. All tests, should be using `./singularity` even though it says `singularity`
6. Some help page is too long and will use a pager to view the help content. In this case, use `q` to exit and `ctrl+u` and `ctrl-d` to scroll up and down

#### Use SQLite3
```
singularity admin reset
```
#### Use MYSQL
```export DATABASE_CONNECTION_STRING="mysql://user:pass@tcp(localhost:3306)/dbname?parseTime=true"
singularity admin reset
```

#### Use Postgres
```
export DATABASE_CONNECTION_STRING=postgres://user:pass@example.com:5432/dbname
singularity admin reset
```

### Inline preparation
Read what inline preparation means [here](https://data-programs.gitbook.io/singularity/topics/inline-preparation)
In short
* To enable inline preparation, do not supply `--output-dir` in `singularity dataset create`
* To disable inline preparation, supply `--output-dir` in `singularity dataset create`

### WebAPI
To run webAPI, use
```
singularity run api
```
And then go to http://127.0.0.1:9090/swagger/index.html
Most CLI actions have a corresponding WebAPI

### Known issues
* We are using [urfave/cli](https://github.com/urfave/cli) which requires the command options to be before the command args. Make sure you use `singularity command --key1 value1 --key2 value2 arg1 arg2` instead of `singularity command arg1 arg2 --key1 value1 --key2 value2`

# Test list
- [x] dataset creation `singularity dataset create`
- [x] try different `--max-size` and `--piece-size` options
- [x] dataset list `singularity dataset list`
- [x] dataset update `singularity dataset update`
- [x] add a datasource `singularity datasource add local test <local_path>`. The data source needs to contain file of different types
  - [x] Empty file
  - [x] Large number of small regular file (>100k in a folder)
  - [x] Nested folder
  - [x] Empty folder
  - [x] File > sector size
- [x] run dataset prep worker `singularity run dataset-worker --exit-on-error --exit-on-complete`
- [x] trigger daggen `singularity datasource daggen 1`
- [x] run dataset prep worker again `singularity run dataset-worker --exit-on-error --exit-on-complete`
- [x] check various datasource commands after or in the middle of above data preparation process. If the command is not clear, please provide feedback
  - [x] `singularity datasource list`
  - [x] `singularity datasource status`
  - [x] `singularity datasource remove`
  - [x] `singularity datasource check`
  - [x] `singularity datasource update`
  - [x] `singularity datasource inspect chunks`
  - [x] `singularity datasource inspect items`
  - [x] `singularity datasource inspect dags`
  - [x] `singularity datasource inspect chunkdetail`
  - [x] `singularity datasource inspect itemdetail`
  - [x] `singularity datasource inspect path`
- [ ] Use the tool `singularity tool extract-car` to convert those CAR files back to actual files and verify all files are the same as the original data source. The rootCID comes from singularity datasource inspect path
- [ ] dataset removal `singularity dataset remove` This will remove all revelant informations about this dataset, including linked datasource, chunks, etc. It will not remove deals made so any dashboard related to deals will still be shown

**Comment by jcace** [comment]
Created issue https://github.com/data-preservation-programs/singularity/issues/175

**Comment by jcace** [comment]
Note: for testing the `extract-car`, I had to run the content provider and then download the CARs:

```bash
singularity run content-provider
```

Then, find the piece cids of the CARfiles to download them
```bash
singularity datasource inspect chunkdetail 1 | head -n 15
singularity datasource inspect chunkdetail 2 | head -n 15
```

Then download the carfiles from the server 
```bash
curl localhost:7777/piece/baga6ea4seaqcbp33kmi5peejpjgrk4dyrdxdhwe4exodhnjoxcqe44svmmi2eli --output /srv/singularity/test/baga6ea4seaqcbp33kmi5peejpjgrk4dyrdxdhwe4exodhnjoxcqe44svmmi2eli.car

curl localhost:7777/piece/baga6ea4seaqhd2lxgalclfzruywctmma4sai3tigjmbnh4ahx2fhk22fbxoimgi --output /srv/singularity/test/baga6ea4seaqhd2lxgalclfzruywctmma4sai3tigjmbnh4ahx2fhk22fbxoimgi.car 
```

Then, grab the root CID 
```bash
singularity datasource inspect path 1
```

Then try to extract
```bash
./singularity tool extract-car --input-dir /srv/singularity/test/ --output /srv/singularity/test-out --cid bafybeicfseigqikarzsknxtmy2snylailkmi65xzhld7l3qyqfmhiwr6uy
```

**Comment by jcace** [comment]
Created issue #210

**Comment by xinaxu** [comment]
Launching MVP v0.5.0. Above list is also covered in unit test.
