### ISSUE TITLE
Dataset preparation with public S3 bucket

### ISSUE THREAD

**Issue by xinaxu** [data-preservation-programs/singularity#96]
## Prerequisite
Make sure you've already tested #90 with any platform / database backend

# Test List
- [ ] Create an S3 bucket that is public - verify it's public by downloading the HTTP link of any entry
- [ ] The bucket needs to contain different types of files
  - [ ] Large number of small regular file (>100k in a folder)
  - [ ] Nested folder
  - [ ] Empty folder
  - [ ] File Size > sector size
  - [ ] Inaccessible file or folder
- [ ] Instead of adding a local data source, add an S3 data source `singularity datasource add s3 test <options> <bucket_name>`.  You may need to use below options
  - [ ] `--s3-provider AWS`
  - [ ] `--s3-region <region>`
- [ ] Perform the rest steps from #90

**Comment by beck-8** [comment]
Starting at almost the same time, the worker's concurrency is 50, it seems that the scanning and generation of small files is much slower than that of large files
|bucket|number of files|average size(MiB)|
|--|--|--|
|noaa-gefs-retrospective|9771083|41.76668842|
|noaa-cfs-pds|71849162|5.66106297|

```bash
root@hostname:~/beck/singularity# ./singularity datasource status 1
2023-08-02T09:42:12.484+0800    INFO    database        database/connstring_cgo.go:26   Opening sqlite database (cgo version)
Chunks by state:
Count  State
544    complete
2      error
5      processing
3      ready

Items by state:
Total    Prepared
1486028  1453419

root@hostname:~/beck/singularity# ./singularity datasource status 2
2023-08-02T09:42:16.376+0800    INFO    database        database/connstring_cgo.go:26   Opening sqlite database (cgo version)
Chunks by state:
Count  State
3037   complete
1      error
43     processing
25     ready

Items by state:
Total    Prepared
1367670  1336699

root@hostname:~/beck/singularity# ./singularity datasource list
2023-08-02T09:42:31.282+0800    INFO    database        database/connstring_cgo.go:26   Opening sqlite database (cgo version)
ID  DatasetID  Type  Path                     ScanIntervalSeconds  ScanningState  LastScannedPath                                                                   ErrorMessage  DeleteAfterExport  DagGenState  DagGenErrorMessage
1   1          s3    noaa-cfs-pds             0                    processing     cfs.20181125/18/time_grib_01/csusf.01.2018112518.daily.grb2.idx                                 false
2   1          s3    noaa-gefs-retrospective  0                    processing     GEFSv12/reforecast/2002/2002100600/p03/Days:1-10/pvort_isen_2002100600_p03.grib2                false
```

**Comment by xinaxu** [comment]
This is kind of inevitable because smaller files have higher network overhead and should be using a larger worker thread count. 

Another approach is to have some prefetching during packing 
#344

**Comment by xinaxu** [comment]
@beck-8 I wouldn't have time to add this optimization for the MVP launch but will take a look in October. Meanwhile, check out this page
https://data-programs.gitbook.io/singularity/data-preparation/performance-tuning

It does not address above performance challenge but might help other areas
